spring:
  application:
    name: Trabalho Back End
  datasource:
    url: jdbc:h2:mem:musicas
    username: sa
    password: ""
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
